[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "snakemake_example"
version = "0.1.0"
dependencies = ["snakemake"]

[tool.setuptools]
py-modules = ["project_setup"]
