local logfile "C:\Users\hms467\github\snakemake_example\analysis\stata_analysis\logs\stata_analysis.log"
local _names "{'stata_results': (0, None)}"
local _allowed_overrides "['index', 'sort']"
local index "<snakemake.io.AttributeGuard object at 0x0000025DFD3C2A80>"
local sort "<snakemake.io.AttributeGuard object at 0x0000025DFD3C1FE0>"
local sim_data_shocked "C:/Users/hms467/github/snakemake_example/dgp/add_shocks/output/sim_data_shocked.csv"
local stata_analysis_code "C:/Users/hms467/github/snakemake_example/analysis/stata_analysis/code/stata_analysis.do"
local ado_example "C:/Users/hms467/github/snakemake_example/utils/ado_files/ado_example.ado"
local stata_results "C:/Users/hms467/github/snakemake_example/analysis/stata_analysis/output/stata_results.tex"
adopath ++ "C:\Users\hms467\github\snakemake_example\utils\ado_files"
