* Simple Stata script to load CSV and export summary stats to TeX
* Uses estout package for clean table formatting
* Author: Generated by GitHub Copilot


* right now the log file goes into the root directory when run from snakefile need to fix 
*log using stata_analysis.log, replace

clear all
set more off


include "`1'stata_analysis_locals.do"


*args logfile input_file output_file

log using "`logfile'", replace

* Load CSV data
import delimited "`sim_data_shocked'", clear



* Basic descriptives
describe



summarize

* ado example
ado_example


su


* Create summary statistics table using estpost
estpost summarize
esttab using "`stata_results'", replace ///
    cells("count(fmt(0)) mean(fmt(3)) sd(fmt(3)) min(fmt(3)) max(fmt(3))") ///
    label title("Summary Statistics") ///
    addnotes("Notes: This table shows descriptive statistics for all variables.") ///
    booktabs

display "Summary statistics exported to: `stata_results'"


cap log close